name: DevOps One-Command Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.29.0

      - name: Install kind
        run: |
          curl -Lo kind https://kind.sigs.k8s.io/dl/v0.23.0/kind-linux-amd64
          chmod +x kind
          sudo mv kind /usr/local/bin/kind

      - name: Create Kubernetes cluster
        run: |
          kind create cluster --name healthcare
          kubectl cluster-info

      - name: Run build
        run: |
          chmod +x dev.sh
          ./dev.sh build

      - name: Run deploy
        run: |
          ./dev.sh deploy

      - name: Show pods and services
        run: |
          kubectl get pods -n healthcare
          kubectl get svc -n healthcare
